## PyTorch Setup

In [24]:
import torch
import numpy as np

np.set_printoptions(precision=3)

In [25]:
!python pytorch_config.py

torch version: 1.11.0+cu113
CUDA is available: True
device count: 1
current device: 0
device 0 is: NVIDIA GeForce RTX 2070 SUPER


## Creating Tensors in PyTorch

In [26]:
# convert list and numpy array to tensor
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)

t_a = torch.tensor(a)
t_b = torch.from_numpy(b)

print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [27]:
# inspect properties of tensor
t_ones = torch.ones(3, 2)
print(t_ones.shape)
print(t_ones)

torch.Size([3, 2])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [28]:
# create random values
rand_tensor = torch.rand(2, 3)
print(rand_tensor)

tensor([[0.4359, 0.7515, 0.5640],
        [0.6844, 0.3030, 0.5835]])


## Manipulating the Data Type and Shape of a Tensor

In [29]:
# change data type of tensor
t_a_new = t_a.to(torch.int64)
print(t_a_new.dtype)

torch.int64


In [30]:
# transposing a tensor
t = torch.rand(3, 5)
t_tr = torch.transpose(t, 0, 1)
print(t.shape, ' --> ', t_tr.shape)

torch.Size([3, 5])  -->  torch.Size([5, 3])


In [31]:
# reshaping a tensor
t = torch.zeros(30)
t_reshape = t.reshape(5, 6)
print(t.shape, ' --> ', t_reshape.shape)

torch.Size([30])  -->  torch.Size([5, 6])


In [33]:
# squeeze dimensions 
t = torch.zeros(1, 2, 1, 4, 1)
t_sqz = torch.squeeze(t, 2)
print(t.shape, ' --> ', t_sqz.shape)

torch.Size([1, 2, 1, 4, 1])  -->  torch.Size([1, 2, 4, 1])


## Applying Mathematical Operations to Tensors

In [34]:
torch.manual_seed(1)
t1 = 2 * torch.rand(5, 2) - 1
t2 = torch.normal(mean=0, std=1, size=(5, 2))

In [36]:
# compute element-wise product
t3 = torch.multiply(t1, t2)
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


In [37]:
# mean of each column
t4 = torch.mean(t1, axis=0)
print(t4)

tensor([-0.1373,  0.2028])


In [39]:
# matrix multiplication: t_1 x t_2^T
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))
print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [40]:
# matrix multiplication: t_1^T x t_2
t6 = torch.matmul(torch.transpose(t1, 0, 1), t2)
print(t6)

tensor([[ 1.7453,  0.3392],
        [-1.6038, -0.2180]])


In [45]:
# L^2 norm of t1
norm_t1 = torch.linalg.norm(t1, ord=2, dim=1)
print(norm_t1)

# compare with base operations
base_norm_t1 = torch.tensor(np.sqrt(np.sum(np.square(t1.numpy()), axis=1)))
print(base_norm_t1)

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])
tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])


## Split, Stack, and Concatenate Tensors

In [50]:
# split tensors using torch.chunk(tensor, chunks)
# if the number of chunks is not divisible by the tensor size, the final chunk will be smaller.

torch.manual_seed(1)
t = torch.rand(6)
print(t)

t_splits = torch.chunk(t, 3)
[item.numpy() for item in t_splits]

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])


[array([0.758, 0.279], dtype=float32),
 array([0.403, 0.735], dtype=float32),
 array([0.029, 0.8  ], dtype=float32)]

In [51]:
# define size of output tensors directly with torch.split(tensor, split_size_or_sections)

torch.manual_seed(1)
t = torch.rand(5)
print(t)

t_splits = torch.split(t, split_size_or_sections=[3, 2])
[item.numpy() for item in t_splits]

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])


[array([0.758, 0.279, 0.403], dtype=float32),
 array([0.735, 0.029], dtype=float32)]